INSERT INTO Songs
VALUES
    (NULL,"Driving with the Top Down","3:10"),
    (NULL,"Iron Man (2008 version)","1:05"),
    (NULL,"Merchant of Death","2:14"),
    (NULL,"Trinkets to Kill a Prince","3:07"),
    (NULL,"Mark I","3:53"),
    (NULL,"Fireman","2:09"),
    (NULL,"Vacation's Over","3:34"),
    (NULL,"Golden Egg","4:12"),
    (NULL,"Damn Kid","1:12"),
    (NULL,"Mark II","2:47"),
    (NULL,"Extra Dry, Extra Olives","1:43"),
    (NULL,"Iron Man","3:30"),
    (NULL,"Gulmira","4:05"),
    (NULL,"Are Those Bullet Holes?","2:00"),
    (NULL,"Section 16","2:33"),
    (NULL,"Iron Monger","4:45"),
    (NULL,"Arc Reaktor","3:55"),
    (NULL,"Institutionalized","3:49"),
    (NULL,"Iron Man (1966 version)","0:20"),
    (NULL,"The Arctic","2:46"),
    (NULL,"Main Title","2:38"),
    (NULL,"Rocinha Favela","3:11"),
    (NULL,"A Drop of Blood","1:35"),
    (NULL,"The Flower","2:49"),
    (NULL,"Ross's Team","1:33"),
    (NULL,"Mr. Blue","1:03"),
    (NULL,"Favela Escape","3:35"),
    (NULL,"It Was Banner","1:31"),
    (NULL,"That Is the Target","5:33"),
    (NULL,"Bruce Goes Home","1:24"),
    (NULL,"Ross and Blonsky","3:15"),
    (NULL,"Return to Culver University","2:38"),
    (NULL,"The Lab","1:16"),
    (NULL,"Reunion","3:37"),
    (NULL,"The Data/The Vial","1:20"),
    (NULL,"They're Here","3:06"),
    (NULL,"Give Him Everything You've Got","6:08"),
    (NULL,"Bruce Can't Stay","1:53"),
    (NULL,"First Injection","1:02"),
    (NULL,"Is It Safe?","1:06"),
    (NULL,"Hulk Theme","3:59"),
    (NULL,"Saved from the Flames","0:53"),
    (NULL,"Grotto","2:53"),
    (NULL,"Arrival at the Motel","1:47"),
    (NULL,"I Can't","2:15"),
    (NULL,"Abomination Alley","3:56"),
    (NULL,"They Found Bruce","2:51"),
    (NULL,"Bruce Looks for the Data","1:05"),
    (NULL,"Cab Ride in NYC","1:17"),
    (NULL,"The Mirror","1:17"),
    (NULL,"Stern's Lab","4:16"),
    (NULL,"Bruce Darted","3:00"),
    (NULL,"I Want It, I Need It","1:35"),
    (NULL,"Blonsky Transforms","1:15"),
    (NULL,"Bruce Must Do It","2:11"),
    (NULL,"Harlem Brawk","3:50"),
    (NULL,"Are They Dead?","2:40"),
    (NULL,"Hulk Smash","2:24"),
    (NULL,"Hulk and Betty","1:49"),
    (NULL,"A Tear","1:00"),
    (NULL,"Who's We?","0:55"),
    (NULL,"The Necklace","1:44"),
    (NULL,"Bruce and Betty","5:06"),
    (NULL,"Hulk Theme (End Credits)","3:58"),
    (NULL,"Ivan's Metamorphosis","5:47"),
    (NULL,"House Fight V1","5:47"),
    (NULL,"Making Pepper CEO","1:08"),
    (NULL,"Senate / Ivan Creates Drones","3:37"),
    (NULL,"Make Way for Tomorrow - Expo Version","0:53"),
    (NULL,"Rhodey Dons Suit","0:56"),
    (NULL,"Dying Hero","1:51"),
    (NULL,"Natalie Intro","1:03"),
    (NULL,"Monaco Drive","0:41"),
    (NULL,"Mayhem in Monaco","7:25"),
    (NULL,"Jailhouse Talk","2:24"),
    (NULL,"Ivan Escapes","1:42"),
    (NULL,"Gun Show","2:10"),
    (NULL,"Tony Discovers Dad's Secret","4:09"),
    (NULL,"Sledgehammer V2","2:39"),
    (NULL,"Nick Fury","1:29"),
    (NULL,"New Element / Particle Accelerator","6:14"),
    (NULL,"Sledgehammer","1:07"),
    (NULL,"New RT / To the Expo","1:43"),
    (NULL,"Black Widow Kicks Ass","2:11"),
    (NULL,"Iron Man Battles the Drones","8:00"),
    (NULL,"Ivan's Demise / The Kiss","5:05"),
    (NULL,"Thor","0:39"),
    (NULL,"I Am Iron Man","1:30"),
    (NULL,"Make Way for Tomorrow Today","1:51"),
    (NULL,"Chasing the Storm","3:11"),
    (NULL,"Prologue","3:09"),
    (NULL,"Sons of Odin","1:48"),
    (NULL,"A New King","3:00"),
    (NULL,"Ride to Observatory","2:10"),
    (NULL,"To Jotunheim","2:19"),
    (NULL,"Laufey","3:40"),
    (NULL,"Frost Giant Battle","4:22"),
    (NULL,"Banishment","1:53"),
    (NULL,"Crisis In Asgard","2:18"),
    (NULL,"Odin Confesses","2:43"),
    (NULL,"Hammer Found","1:11"),
    (NULL,"Urgent Matter","2:21"),
    (NULL,"The Compound","7:40"),
    (NULL,"Loki's Lie","1:54"),
    (NULL,"My Bastard Son","2:39"),
    (NULL,"Science and Magic","2:53"),
    (NULL,"The Destroyer","2:57"),
    (NULL,"Forgive Me","2:40"),
    (NULL,"Thor Kills the Destroyer","1:53"),
    (NULL,"Brothers Fight","6:59"),
    (NULL,"Letting Go","3:17"),
    (NULL,"Can You See Jane?","2:23"),
    (NULL,"Earth to Asgard","2:33"),
    (NULL,"Captain America Main Titles","0:56"),
    (NULL,"Frozen Wasteland","1:53"),
    (NULL,"Schmidt's Treasure","3:01"),
    (NULL,"Farewell to Bucky","2:50"),
    (NULL,"Hydra Lab","1:54"),
    (NULL,"Training the Supersoldier","1:08"),
    (NULL,"Schmidt's Story","1:59"),
    (NULL,"VitaRays","4:25"),
    (NULL,"Captain America 'We Did It'","1:59"),
    (NULL,"Kruger Chase","2:55"),
    (NULL,"Hostage On the Pier","2:46"),
    (NULL,"General's Resign","2:18"),
    (NULL,"Unauthorized Night Flight","3:13"),
    (NULL,"Troop Liberation","5:06"),
    (NULL,"Factory Inferno","5:06"),
    (NULL,"Triumphant Return","2:16"),
    (NULL,"Howling Commando's Montage","2:16"),
    (NULL,"Hydra Train","3:27"),
    (NULL,"'Rain Fire Upon Them'","1:39"),
    (NULL,"Motorcycle Mayhem","3:05"),
    (NULL,"Invasion","5:09"),
    (NULL,"Fight on the Flight Deck","3:30"),
    (NULL,"This is My Choice","3:26"),
    (NULL,"Passage of Time","1:35"),
    (NULL,"Captain America","1:08"),
    (NULL,"Star Spangled Man","2:53"),
    (NULL,"Captain America March","2:36"),
    (NULL,"Arrival","2:59"),
    (NULL,"Doors Open From Both Sides","2:48"),
    (NULL,"Tunnel Chase","2:36"),
    (NULL,"Stark Goes Green","2:41"),
    (NULL,"Helicarrier","2:09"),
    (NULL,"Subjugation","3:00"),
    (NULL,"Don't Take My Stuff","4:42"),
    (NULL,"Red Ledger","5:11"),
    (NULL,"Assault","4:26"),
    (NULL,"They Called It","2:41"),
    (NULL,"Performance Issues","3:35"),
    (NULL,"Seeing, Not Believing","4:25"),
    (NULL,"Assemble","4:31"),
    (NULL,"I Got a Ride","4:00"),
    (NULL,"A Little Help","3:14"),
    (NULL,"One Way Trip","5:50"),
    (NULL,"A Promise","3:34"),
    (NULL,"The Avengers","2:03"),
    (NULL,"Iron Man 3",",2:24"),
    (NULL,"War Machine","7:19"),
    (NULL,"Attack on 10880 Malibu Point","4:36"),
    (NULL,"Isolation","2:01"),
    (NULL,"Dive Bombers","2:24"),
    (NULL,"New Beginnings","3:55"),
    (NULL,"Extremis","5:07"),
    (NULL,"Stark","4:32"),
    (NULL,"Leverage","2:16"),
    (NULL,"The Mandarin","2:37"),
    (NULL,"Heat and Iron","5:43"),
    (NULL,"Misfire","3:27"),
    (NULL,"Culmination","2:30"),
    (NULL,"The Mechanic","3:44"),
    (NULL,"Hot Pepper","4:42"),
    (NULL,"Another Lesson from the Mandarin","2:57"),
    (NULL,"Dr. Wu","2:41"),
    (NULL,"Return","6:20"),
    (NULL,"Battle Finale","3:57"),
    (NULL,"Can You Dig It (Iron Man 3 Main Titles)","2:42"),
    (NULL,"Thor: The Dark World","2:10"),
    (NULL,"Lokasenna","2:31"),
    (NULL,"Asgard","1:55"),
    (NULL,"Battle of Vanaheim","1:39"),
    (NULL,"Origins","3:49"),
    (NULL,"The Trial of Loki","2:38"),
    (NULL,"Into Eternity","3:40"),
    (NULL,"Escaping the Realm","3:53"),
    (NULL,"A Universe from Nothing","2:20"),
    (NULL,"Untouchable","4:08"),
    (NULL,"Thor, Son of Odin","1:51"),
    (NULL,"Shadows of Loki","2:25"),
    (NULL,"Sword and Council","3:46"),
    (NULL,"Invasion of Asgard","2:59"),
    (NULL,"Betrayal","4:02"),
    (NULL,"Journey to Asgard","2:17"),
    (NULL,"Uprising","2:35"),
    (NULL,"Vortex","2:20"),
    (NULL,"An Unlikely Alliance","3:47"),
    (NULL,"Convergence","3:42"),
    (NULL,"Beginning of the End","5:20"),
    (NULL,"Deliverance","2:21"),
    (NULL,"Battle Between Worlds","3:29"),
    (NULL,"As the Hammer Falls","2:40"),
    (NULL,"Legacy","4:08"),
    (NULL,"Marvel Studios Fanfare","0:29"),
    (NULL,"Lemurian Star","3:06"),
    (NULL,"Project Insight","1:29"),
    (NULL,"The Smithsonian","1:36"),
    (NULL,"An Old Friend","3:05"),
    (NULL,"Fury","4:07"),
    (NULL,"The Winter Soldier","6:24"),
    (NULL,"Fallen","2:51"),
    (NULL,"Alexander Pierce","2:58"),
    (NULL,"Taking a Stand","2:07"),
    (NULL,"Frozen in Time","3:52"),
    (NULL,"Hydra","6:46"),
    (NULL,"Natasha","1:12"),
    (NULL,"The Causeway","2:41"),
    (NULL,"Time to Suit Up","2:05"),
    (NULL,"Into the Fray","6:05"),
    (NULL,"Countdown","4:26"),
    (NULL,"End of the Line","2:51"),
    (NULL,"Captain America","9:41"),
    (NULL,"It's Been a Long, Long Time","3:23"),
    (NULL,"Trouble Man","3:47"),
    (NULL,"Morag","1:58"),
    (NULL,"The Final Battle Begins","4:21"),
    (NULL,"Plasma Ball","1:18"),
    (NULL,"Quill's Big Retreat","1:38"),
    (NULL,"To the Stars","2:52"),
    (NULL,"Ronan's Theme","2:24"),
    (NULL,"Everyone's an Idiot","1:26"),
    (NULL,"What a Bunch of A-Holes","2:14"),
    (NULL,"Busted","1:34"),
    (NULL,"The New Meat","0:36"),
    (NULL,"The Destroyer","1:27"),
    (NULL,"Sanctuary","2:26"),
    (NULL,"The Kyln Escape","7:23"),
    (NULL,"Don't Mess With My Walkman","0:44"),
    (NULL,"The Great Companion","0:51"),
    (NULL,"The Road to Knowhere","0:37"),
    (NULL,"The Collector","3:20"),
    (NULL,"Ronan's Arrival","0:56"),
    (NULL,"The Pod Chase","3:56"),
    (NULL,"Sacrifice","3:20"),
    (NULL,"We All Got Dead People","1:46"),
    (NULL,"The Ballad of the Nova Corps.","1:48"),
    (NULL,"Groot Spores","1:11"),
    (NULL,"Guardians United","2:46"),
    (NULL,"The Big Blast","3:05"),
    (NULL,"Groot Cocoon","2:29"),
    (NULL,"Black Tears","2:43"),
    (NULL,"Citizens Unite","1:15"),
    (NULL,"A Nova Upgrade","2:10"),
    (NULL,"Avengers: Age of Ultron Title","0:43"),
    (NULL,"Heroes","2:07"),
    (NULL,"Rise Together","2:23"),
    (NULL,"Breaking and Entering","3:04"),
    (NULL,"It Begins","2:42"),
    (NULL,"Birth of Ultron","3:05"),
    (NULL,"Ultron-Twins","4:13"),
    (NULL,"Hulkbuster","4:32"),
    (NULL,"Can You Stop This Thing?","1:03"),
    (NULL,"Sacrifice","2:42"),
    (NULL,"Farmhouse","4:02"),
    (NULL,"The Vault","2:58"),
    (NULL,"The Mission","2:48"),
    (NULL,"Seoul Searching","2:48"),
    (NULL,"Inevitability-One Good Eye","5:07"),
    (NULL,"Ultron Wakes","1:43"),
    (NULL,"Vision","3:47"),
    (NULL,"The Battle","4:24"),
    (NULL,"Wish You Were Here","1:36"),
    (NULL,"The Farm","1:14"),
    (NULL,"Darkest of Intentions","2:26"),
    (NULL,"Fighting Back","2:33"),
    (NULL,"Avengers Unite","1:08"),
    (NULL,"Keys to the Past","1:48"),
    (NULL,"Uprising","2:32"),
    (NULL,"Outlook","2:38"),
    (NULL,"The Last One","2:14"),
    (NULL,"Nothing Lasts Forever","1:57"),
    (NULL,"New Avengers - Avengers: Age of Ultron","3:09"),
    (NULL,"Theme from Ant-Man","2:46"),
    (NULL,"Honey, I Shrunk Myself","2:29"),
    (NULL,"Escape from Jail","1:51"),
    (NULL,"Ant 247","1:13"),
    (NULL,"Paraponera Clavata","1:24"),
    (NULL,"San Francisco, 1987","2:37"),
    (NULL,"I'll Call Him Antony","2:50"),
    (NULL,"Tiny Telepathy","2:02"),
    (NULL,"First Mission","3:23"),
    (NULL,"Signal Decoy","0:51"),
    (NULL,"Old Man Have Safe","2:25"),
    (NULL,"Pym's Lab","1:26"),
    (NULL,"Antfiltration","1:20"),
    (NULL,"Your Mom Died a Hero","2:03"),
    (NULL,"Scott Surfs on Ants","1:11"),
    (NULL,"The Water Main","1:14"),
    (NULL,"CrossTech Break-In","1:47"),
    (NULL,"Into the Hornet's Nest","3:00"),
    (NULL,"Become the Hero","1:52"),
    (NULL,"Insecticide","2:51"),
    (NULL,"A Center for Ants!","1:15"),
    (NULL,"Cross Gets Cross","1:52"),
    (NULL,"Fight of the Bumblebee","1:44"),
    (NULL,"Ants on a Train","1:43"),
    (NULL,"Small Sacrifice","3:36"),
    (NULL,"About Damn Time","0:39"),
    (NULL,"Tales to Astonish!","1:47"),
    (NULL,"Borombon","2:49"),
    (NULL,"Escape","2:14"),
    (NULL,"I'm Ready","3:20"),
    (NULL,"Pink Gorilla","3:46"),
    (NULL,"Siberian Overture","2:56"),
    (NULL,"Lagos","2:10"),
    (NULL,"Consequences","2:22"),
    (NULL,"Ancestral Call","2:37"),
    (NULL,"Zemo","3:09"),
    (NULL,"The Tunnel","3:51"),
    (NULL,"Celestial Bodies","1:44"),
    (NULL,"Boot Up","5:16"),
    (NULL,"A New Recruit","1:47"),
    (NULL,"Stepping Up","1:59"),
    (NULL,"Standoff","4:01"),
    (NULL,"Civil War","4:26"),
    (NULL,"Larger Than Life","3:40"),
    (NULL,"Catastrophe","2:36"),
    (NULL,"Revealed","5:38"),
    (NULL,"Making Amends","1:34"),
    (NULL,"Fracture","4:00"),
    (NULL,"Clash","3:54"),
    (NULL,"Closure","5:32"),
    (NULL,"Cap's Promise","3:46"),
    (NULL,"Adagio","2:18"),
    (NULL,"Ancient Sorcerer's Secret","2:37"),
    (NULL,"The Hands Dealt","2:56"),
    (NULL,"A Long Strange Trip","2:28"),
    (NULL,"The Eyes Have It","1:23"),
    (NULL,"Mystery Training","1:53"),
    (NULL,"Reading Is Fundamental","1:39"),
    (NULL,"Inside the Mirror Dimension","4:04"),
    (NULL,"The True Purpose of the Sorcerer","2:09"),
    (NULL,"Sanctimonious Sanctum Sacking","7:27"),
    (NULL,"Astral Doom","3:41"),
    (NULL,"Post Op Paracosm","1:15"),
    (NULL,"Hippocratic Hypocrite","1:34"),
    (NULL,"Smote and Mirrors","6:29"),
    (NULL,"Ancient History","4:08"),
    (NULL,"Hong Kong Kablooey","3:35"),
    (NULL,"Astral World's Worst Killer","6:17"),
    (NULL,"Strange Days Ahead","5:59"),
    (NULL,"Go for Baroque","2:55"),
    (NULL,"The Master of the Mystic End Credits","3:50"),
    (NULL,"Showtime a-Holes","1:27"),
    (NULL,"vs the Abilisk","2:35"),
    (NULL,"The Mantis Touch","1:53"),
    (NULL,"Space Chase","3:20"),
    (NULL,"Family History","3:48"),
    (NULL,"Groot Expectations","1:57"),
    (NULL,"Mammalian Bodies","1:50"),
    (NULL,"Starhawk","1:49"),
    (NULL,"Two-Time-Galaxy Savers","3:01"),
    (NULL,"I Know Who You Are","4:20"),
    (NULL,"Ego","2:47"),
    (NULL,"Kraglin and Drax","1:34"),
    (NULL,"The Expansion","1:05"),
    (NULL,"Mary Poppins and the Rat","3:07"),
    (NULL,"Gods","1:28"),
    (NULL,"Dad","2:28"),
    (NULL,"A Total Hasselhoff","2:01"),
    (NULL,"Sisters","2:05"),
    (NULL,"Guardians of the Frickin Galaxy","0:59"),
    (NULL,"Theme From Spider-Man (Original Television Series)","0:39"),
    (NULL,"The World is Changing","4:10"),
    (NULL,"Academic Decommitment","1:57"),
    (NULL,"High Tech Heist","1:26"),
    (NULL,"On a Ned-To-Know Basis","1:45"),
    (NULL,"Drag Racing / An Old Van Rundown","4:06"),
    (NULL,"Webbed Surveillance","4:40"),
    (NULL,"No Vault of His Own","2:27"),
    (NULL,"Monumental Meltdown","5:23"),
    (NULL,"The Baby Monitor Protocol","1:37"),
    (NULL,"A Boatload of Trouble Part 1","3:09"),
    (NULL,"A Boatload of Trouble Part 2","2:16"),
    (NULL,"Ferry Dust Up","2:50"),
    (NULL,"Stark Raving Mad","1:54"),
    (NULL,"Pop Vulture","3:05"),
    (NULL,"Bussed a Move","1:43"),
    (NULL,"Lift Off","5:25"),
    (NULL,"Fly-By-Night Operation","2:23"),
    (NULL,"Vulture Clash","4:07"),
    (NULL,"A Stark Contrast","4:41"),
    (NULL,"No Frills Proto COOL!","0:34"),
    (NULL,"Spider-Man: Homecoming Suite","6:13"),
    (NULL,"Ragnarok Suite","8:53"),
    (NULL,"Running Short on Options","2:46"),
    (NULL,"Thor: Ragnarok","1:09"),
    (NULL,"Weird Things Happen","1:46"),
    (NULL,"Twilight of the Gods","6:14"),
    (NULL,"Hela vs. Asgard","4:30"),
    (NULL,"Where am I?","1:39"),
    (NULL,"Grandmaster’s Chambers","1:18"),
    (NULL,"The Vault","3:47"),
    (NULL,"No One Escapes","3:01"),
    (NULL,"Arena Fight","3:32"),
    (NULL,"Where’s the Sword?","4:33"),
    (NULL,"Go","1:43"),
    (NULL,"What Heroes Do","1:37"),
    (NULL,"Flashback","2:59"),
    (NULL,"Parade","2:20"),
    (NULL,"The Revolution Has Begun","1:47"),
    (NULL,"Sakaar Chase","2:12"),
    (NULL,"Devil’s Anus","4:52"),
    (NULL,"Asgard Is a People","4:20"),
    (NULL,"Where To?","2:22"),
    (NULL,"Planet Sakaar","2:14"),
    (NULL,"Grandmaster Jam Session","3:16"),
    (NULL,"Wakanda Origins","1:44"),
    (NULL,"Royal Talon Fighter","4:00"),
    (NULL,"Wakanda","2:20"),
    (NULL,"Warrior Falls","4:06"),
    (NULL,"The Jabari","1:08"),
    (NULL,"Waterfall Fight","4:03"),
    (NULL,"Ancestral Plane","4:27"),
    (NULL,"Killmonger","2:55"),
    (NULL,"Phambili","2:31"),
    (NULL,"Casino Brawl","3:32"),
    (NULL,"Busan Car Chase","2:49"),
    (NULL,"Questioning Klaue","3:32"),
    (NULL,"Outsider","2:07"),
    (NULL,"Is This Wakanda?","2:46"),
    (NULL,"Killmonger's Challenge","5:07"),
    (NULL,"Killmonger vs. T'Challa","3:30"),
    (NULL,"Loyal to the Throne","1:35"),
    (NULL,"Killmonger's Dream","3:15"),
    (NULL,"Burn It All","3:24"),
    (NULL,"Entering Jabariland","2:42"),
    (NULL,"Wake Up T'Challa","6:08"),
    (NULL,"The Great Mound Battle","3:48"),
    (NULL,"Glory to Bast","6:06"),
    (NULL,"The Jabari, Pt. II","2:22"),
    (NULL,"A Kings Sunset","4:28"),
    (NULL,"A New Day","1:47"),
    (NULL,"Spaceship Bugatti","1:23"),
    (NULL,"United Nations / End Titles","7:32"),
    (NULL,"The Avengers","0:25"),
    (NULL,"Travel Delays","2:43"),
    (NULL,"Undying Fidelity","5:05"),
    (NULL,"He Won’t Come Out","2:31"),
    (NULL,"We Both Made Promises","2:22"),
    (NULL,"Help Arrives","4:21"),
    (NULL,"Hand Means Stop","2:37"),
    (NULL,"You Go Right","4:26"),
    (NULL,"Family Affairs","3:51"),
    (NULL,"What More Could I Lose?","3:36"),
    (NULL,"A Small Price","3:17"),
    (NULL,"Even for You","2:14"),
    (NULL,"More Power","4:07"),
    (NULL,"Charge!","3:28"),
    (NULL,"Forge","4:22"),
    (NULL,"Catch","6:04"),
    (NULL,"Haircut and Beard","3:02"),
    (NULL,"A Lot to Figure Out","2:01"),
    (NULL,"The End Game","2:17"),
    (NULL,"I Feel You","2:48"),
    (NULL,"What Did It Cost?","2:25"),
    (NULL,"Porch","0:59"),
    (NULL,"Infinity War","2:35"),
    (NULL,"It Ain’t Over Till the Wasp Lady Stings","2:34"),
    (NULL,"Prologue","3:42"),
    (NULL,"Ghost in the Machine","1:15"),
    (NULL,"World’s Greatest Grandma","1:34"),
    (NULL,"A Little Nudge","3:49"),
    (NULL,"Feds","2:47"),
    (NULL,"Ava’s Story","4:36"),
    (NULL,"Wings & Blasters","1:55"),
    (NULL,"Utmost Ghost","2:28"),
    (NULL,"Tracker Swarm","1:27"),
    (NULL,"Cautious as a Hurricane","2:47"),
    (NULL,"Misdirection","2:38"),
    (NULL,"Quantum Leap","2:53"),
    (NULL,"I Shrink, Therefore I Am","1:57"),
    (NULL,"Partners","1:52"),
    (NULL,"Windshield Wipeout","1:37"),
    (NULL,"Hot Wheels","1:38"),
    (NULL,"Revivification","2:50"),
    (NULL,"A Flock of Seagulls","1:07"),
    (NULL,"San Francisco Giant","0:45"),
    (NULL,"Ghost = Toast","2:54"),
    (NULL,"Reduce Yourself","1:41"),
    (NULL,"Quit Screwing Around","0:46"),
    (NULL,"Anthropodie","4:16"),
    (NULL,"Baba Yaga Lullaby","0:25"),
    (NULL,"Captain Marvel","2:15"),
    (NULL,"Waking Up","1:28"),
    (NULL,"Boarding the Train","1:30"),
    (NULL,"Why Do You Fight?","1:14"),
    (NULL,"Let's Bring Him Home","1:39"),
    (NULL,"Entering Enemy Territory","3:33"),
    (NULL,"Breaking Free","5:24"),
    (NULL,"Hot Pursuit","4:34"),
    (NULL,"Lost the Target","2:10"),
    (NULL,"Lifting Fingerprints","1:31"),
    (NULL,"Finding the Records","5:20"),
    (NULL,"Escaping the Basement","4:23"),
    (NULL,"Photos of Us","1:56"),
    (NULL,"Learning the Truth","3:16"),
    (NULL,"New Clothes","1:04"),
    (NULL,"Space Turbulence","2:58"),
    (NULL,"High Score","2:35"),
    (NULL,"Interrupting Something?","1:30"),
    (NULL,"Trapped","3:19"),
    (NULL,"I'm All Fired Up","3:20"),
    (NULL,"More Problems","8:15"),
    (NULL,"You Could Use a Jump","1:45"),
    (NULL,"This Isn't Goodbye","2:29"),
    (NULL,"Totally Fine","4:29"),
    (NULL,"Arrival","1:49"),
    (NULL,"No Trust","3:08"),
    (NULL,"Where Are They?","3:12"),
    (NULL,"Becoming Whole Again","3:48"),
    (NULL,"I Figured It Out","4:30"),
    (NULL,"Perfectly Not Confusing","4:46"),
    (NULL,"You Shouldn't Be Here","3:33"),
    (NULL,"The How Works","3:50"),
    (NULL,"Snap Out of It","2:24"),
    (NULL,"So Many Stairs","1:51"),
    (NULL,"One Shot","2:04"),
    (NULL,"Watch Each Other's Six","3:56"),
    (NULL,"I Can't Risk This","4:48"),
    (NULL,"He Gave It Away","3:42"),
    (NULL,"The Tool of a Thief","2:58"),
    (NULL,"The Measure of a Hero","3:05"),
    (NULL,"Destiny Fulfilled","4:05"),
    (NULL,"In Plain Sight","3:14"),
    (NULL,"How Do I Look?","2:06"),
    (NULL,"Whatever It Takes","2:56"),
    (NULL,"Not Good","1:53"),
    (NULL,"Gotta Get Out","2:38"),
    (NULL,"I Was Made for This","4:37"),
    (NULL,"Tres Amigos","3:37"),
    (NULL,"Tunnel Scape","3:16"),
    (NULL,"Worth It","4:15"),
    (NULL,"Portals","3:17"),
    (NULL,"Get This Thing Started","4:54"),
    (NULL,"The One","2:08"),
    (NULL,"You Did Good","1:57"),
    (NULL,"The Real Hero","5:54"),
    (NULL,"Five Seconds","1:45"),
    (NULL,"Go Ahead","2:57"),
    (NULL,"Main on End","3:11"),
    (NULL,"Far From Home Suite Home","8:27"),
    (NULL,"It’s Perfect","0:30"),
    (NULL,"World’s Worst Water Feature","7:30"),
    (NULL,"Multiple Realities","3:32"),
    (NULL,"Brad to the Drone","3:32"),
    (NULL,"Change of Plans","2:28"),
    (NULL,"Night Monkey Knows How to Do It","0:19"),
    (NULL,"Mr. One Hundred and One","3:20"),
    (NULL,"Prague Rocked","3:43"),
    (NULL,"Who’s Behind Those Foster Grants","2:57"),
    (NULL,"Power to the People","3:33"),
    (NULL,"Personal Hijinks","3:53"),
    (NULL,"Praguenosis: BAD","1:08"),
    (NULL,"A Lot of ‘Splaining to Do","2:14"),
    (NULL,"The Magical Mysterio Tour","3:21"),
    (NULL,"Taking the Gullible Express/ Spidey Sensitive","5:07"),
    (NULL,"Gloom and Doom","4:16"),
    (NULL,"High and Flighty","2:20"),
    (NULL,"An Internal Battle","1:50"),
    (NULL,"Happy Landings","2:58"),
    (NULL,"Tower of Cower","5:12"),
    (NULL,"Bridging the Trap","1:58"),
    (NULL,"Bridge and Love’s Burning","2:50"),
    (NULL,"Swinging Set","1:47"),
    (NULL,"And Now This…","0:58");

SELECT * FROM Songs;
DELETE FROM Songs;