INSERT INTO Items
VALUES
    (NULL,"Iron Man Armor","Tony Stark","The Iron Man Armor is a mechanical armor with many capabilities, enhancing the user's pysical capabilities and allowing him to fly, shoot energy blast and much more."),
    (NULL,"War Machine Armor","Tony Stark","The War Machine Armor is a militarized version of the Iron Man Armor."),
    (NULL,"Iron Monger Armor","Stark Industries Engineers","The Iron Monger Armor is an enhanced more powerful version on the Mark I Iron Man Armor."),
    (NULL,"Black Widow's Batons","Tony Stark","Black Widow's Batons are electroshock weapons, based on Escrima sticks."),
    (NULL,"Whiplash Armor","Ivan Vanko","The Whiplash armor is a rudimentary harness. The central piece of the harness is an arc reactor and there are custom designed electrified whips that channel the energy produced by the arc reactor."),
    (NULL,"Mjølnir","Dwarfes","Mjølnir is a powerful enchanted war-hammer forged by the Dwarves for the Asgardian Royal Family."),
    (NULL,"Stormbreaker","Eitri","Stormbreaker is an enchanted axe used by Thor. It was forged from Uru on Nidavellir."),
    (NULL,"Scepter",NULL,"The Scepter, occasionally referred to as Loki's Scepter, is a staff weapon that serves as a containment vessel for the Mind Stone, one of the six Infinity Stones."),
    (NULL,"Tesseract","Cosmic Entities","The Tesseract, also called the Cube, is a crystalline cube-shaped containment vessel for the Space Stone, one of the six Infinity Stones."),
    (NULL,"Gungnir",NULL,"Gungnir is a powerful magical spear used by the rulers of Asgard and serves as a symbol of Asgardian power. It's powered by the Odinforce."),
    (NULL,"Hofund",NULL,"Hofund, often simply referred as the Bifrost Sword, is an Asgardian sword used by Heimdall which also served as a key to activate the switch that opens the Bifrost Bridge."),
    (NULL,"Captain America's Shield","Howard Stark","Captain America's Shield is a vibranium shield and the primary defensive and offensive weapon used by Steve Rogers."),
    (NULL,"Super Soldier Serum","Abraham Erskine","The Super Soldier Serum is a chemical solution formulated to superhumanly enhance the human body and mind."),
    (NULL,"Winter Soldier's Prosthetic Arm","HYDRA","Winter Soldier's Prosthetic Arm is a cybernetic implant attached to the Winter Soldier's body to be used in place of his missing left arm."),
    (NULL,"Hawkeye's Bow and Quiver",NULL,"Hawkeye's Bow and Quiver are a pair of specialized tools used by Hawkeye. Serving as his primary weapons, Hawkeye carries a unique, collapsible recurve bow along with a mechanized quiver that stores and deploys his trick arrows."),
    (NULL,"Extremis","Maya Hansen","Extremis is an advanced form of genetic manipulation using nanotechnology. It grants the human body the ability to heal and regenerate from physical damages, deformities and even psychological damages."),
    (NULL,"Kurse Stone","Dark Elves","The Kurse Stone is a mystical stone used by elite Dark Elves to improve their physical capabilities beyond a normal Dark Elf, but at the cost of certain death some time after the transformation."),
    (NULL,"EXO-7 Falcon","Air National Guard","The EXO-7 Falcon is an experimental, military-designed winged harness created for the Air National Guard to be used during highly sensitive missions"),
    (NULL,"Quad Blasters",NULL,"The Quad Blaster has two separate triggers and barrels, for the index and middle finger respectively. Both of which can be fired at the same time and have a lethal and non-lethal attack function."),
    (NULL,"Star-Lord's Helmet",NULL,"This helmet utilizes a wide array of capabilities, including Size-Altering, Oxygen Purification, Pressure Support, Heads-Up Display and Thermal Vision"),
    (NULL,"Godslayer",NULL,"The Godslayer is a collapsible sword which includes a detachable knife that connects to the sword's hilt."),
    (NULL,"Drax the Destroyer's Knives",NULL,"Drax the Destroyer's Knives are a pair of powerful knives with intricate carvings"),
    (NULL,"Laser Cannon",NULL,"The Laser Cannon, or Rifle Cannon, is a weapon obtained by Rocket Raccoon from a confiscated weapons case in a customs station in the Uptown district of The Hub."),
    (NULL,"Cosmi-Rod","Kree","The Cosmi-Rod is a Kree war-hammer that projects concussive blasts and is given to certain members of the Kree race."),
    (NULL,"Orb",NULL,"The Orb is an ancient artifact that housed the Power Stone, one of the six Infinity Stones."),
    (NULL,"Yaka Arrow","Centaurians","The Yaka Arrow is a whistle-controlled arrow made from Yaka that uses technology native to the Centaurian people."),
    (NULL,"Ant-Man Suit","Hank Pym","The Ant-Man Suit is a suit to maximize the use of the Pym Particles which allow Size Manipulation while also protecting the wearer from the negative side-effects of using Pym Particles."),
    (NULL,"Wasp Suit","Hank Pym","The Wasp Suit is an advanced Pym Particle-based suit, similar to the Ant-Man Suit."),
    (NULL,"Yellowjacket Suit","Darren Cross","The Yellowjacket Suit is a powered suit created that used Darren Cross' version of Hank Pym's Pym Particles."),
    (NULL,"Panther Habit","T'Challa","The Panther Habit is a uniquely crafted Vibranium-weave suit. The vibranium composition makes the user completely bulletproof and near-indestructible."),
    (NULL,"Spider-Man Suit","Tony Stark","The Spider-Man Suit is a specialized suit to hide Peter Parker's identity as Spider-Man. It has a variety of features such as an artificial intelligent system."),
    (NULL,"Iron Spider Armor","Tony Stark","The Iron Spider Armor is a highly modified version of the Spider-Man Suit with a vast amount of added features."),
    (NULL,"Web-Shooters","Peter Parker","The Web-Shooters are a pair of wrist-mounted mechanical devices developed to project Synthetic Webbing."),
    (NULL,"Cloak of Levitation",NULL,"The Cloak of Levitation is a magical relic that is able to move and fly on its own power, enabling its user to levitate and hover in the air."),
    (NULL,"Sling Ring","Masters of the Mystic Arts","A Sling Ring is a mystical object which enables the wearer to open a dimensional gateway to another location."),
    (NULL,"Eye of Agamotto","Agamotto","The Eye of Agamotto is a powerful relic created by the first Sorcerer Supreme, to contain the power of the Time Stone, one of the six Infinity Stones."),
    (NULL,"Staff of the Living Tribunal","Masters of the Mystic Arts","The Staff of the Living Tribunal is a relic used for training and combat, that can extend into interlinked segments as a whip or flail."),
    (NULL,"Scythe Daggers",NULL,"The Scythe Daggers are a pair of curved daggers that resemble kamas."),
    (NULL,"Vulture's Exo Suit","Tinkerer","Vulture's Exo-Suit is a specialized flying mechanical suit created by using salvaged Chitauri technology"),
    (NULL,"Necroswords","Hela","The Necroswords are obsidian swords generated and handled by the Asgardian Goddess of Death, Hela."),
    (NULL,"Double-Edged Sword",NULL,"The Double-Edged Sword is an extremely sturdy double-bladed weapon."),
    (NULL,"Infinity Gauntlet","Eitri","The Infinity Gauntlet is a powerful Dwarven-made Uru glove that's designed to channel the power of all six Infinity Stones."),
    (NULL,"Nano Gauntlet","Tony Stark","The Nano Gauntlet is a glove made of nano-technology. It's designed to contain and allow the user to channel the powers of the Infinity Stones in a manner similar to the Infinity Gauntlet, although the effects of wielding it are far more damaging to the user than the Infinity Gauntlet."),
    (NULL,"Cull Obsidian's Chain Hammer",NULL,"Cull Obsidian's Chain Hammer is a massive sturdy hammer capable of transforming into a variety of different shapes to fit the users needs in combat."),
    (NULL,"Proxima Midnight's Spear",NULL,"Proxima Midnight's Spear is a powerful and dangerous three-pronged spear. It can fire powerful blasts of blue energy."),
    (NULL,"Corvus Glaive's Glaive",NULL,"Corvus Glaive's Glaive is a large scythe. The glaive was created from an incredibly strong, extraterrestrial metal, as it can even pierce the extremely durable skin of an Asgardian."),
    (NULL,"Ghost Suit","S.H.I.E.L.D.","The Ghost Suit is a full-body suit designed by S.H.I.E.L.D. in order to help the user to better control it's phasing powers."),
    (NULL,"Pym Particles","Hank Pym","Pym Particles (also known as Cross Particles) are subatomic particles of an extra dimensional nature that are capable of shunting or adding mass and reducing or increasing scale of any form of matter, compressing physical forces around such objects or organisms that they are applied to, as well as increasing density and strength of the subject."),
    (NULL,"Magnitron Gauntlets","Kree","The Magnitron Gauntlets allow its user to manipulate gravity in a way akin to telekinesis. The gauntlets could also create a barrier of gravitational energy that could deflect energy blasts."),
    (NULL,"Mysterio Suit","Janice Lincoln","The Mysterio Suit is a deceptive costume designed to look like a blend of Iron Man's and Thor's costumes."),
    (NULL,"B.A.R.F.","Quentin Beck","Binarily Augmented Retro-Framing, better known by its acronym B.A.R.F., is a prototype holographic illusion system technology."),
    (NULL,"Space Stone","Cosmic Entities","As the Infinity Stone that represents and governs over space, the Space Stone grants the wielder absolute control over space itself. It is primarily used to open portals to other locations and can even allow interdimensional travel."),
    (NULL,"Reality Stone","Cosmic Entities","As the Infinity Stone that represented and governs over reality, the Reality Stone granted its user absolute control over reality itself."),
    (NULL,"Power Stone","Cosmic Entities","As the Infinity Stone that embodies both the sustaining and destructive forces of the universe, the Power Stone grants its wielder tremendous energy manipulation capabilities. Due to the amount of energy the Power Stone releases, it is the most destructive out of all the Infinity Stones in terms of raw power."),
    (NULL,"Soul Stone","Cosmic Entities","The Soul Stone ranks as possibly the most dangerous of all the Infinity Stones. The Soul Stone has the ability to manipulate the soul, the essence that makes up an individual, and has the ability to resurrect and conjure the spiritual representation of the people who are dead."),
    (NULL,"Mind Stone","Cosmic Entities","As the Infinity Stone that represents and governs the fabric of mind, the Mind Stone grants whoever holds it complete control over the hearts and minds of others."),
    (NULL,"Time Stone","Cosmic Entities","As the Infinity Stone that represents and governs over the flow of time, the Time Stone is among the most powerful artifacts in all existence.");
    
SELECT * FROM Items;
DELETE FROM Items;