INSERT INTO GroupCharacters
VALUES
    (NULL,1,19,"Former"),
    (NULL,1,1,"Former"),
    (NULL,1,11,"Former"),
    (NULL,1,8,"Current"),
    (NULL,1,14,"Former"),
    (NULL,1,22,"Former"),
    (NULL,1,40,"Current"),
    (NULL,1,39,"Former"),
    (NULL,1,41,"Former"),
    (NULL,1,2,"Current"),
    (NULL,1,28,"Current"),
    (NULL,1,47,"Current"),
    (NULL,1,33,"Former"),
    (NULL,1,68,"Current"),
    (NULL,1,36,"Former"),
    (NULL,1,42,"Current"),
    (NULL,2,13,"Current"),
    (NULL,2,27,"Former"),
    (NULL,2,23,"Current"),
    (NULL,2,5,"Former"),
    (NULL,2,11,"Former"),
    (NULL,2,22,"Former"),
    (NULL,2,19,"Former"),
    (NULL,2,67,"Former"),
    (NULL,3,21,"Former"),
    (NULL,3,27,"Former"),
    (NULL,3,20,"Former"),
    (NULL,4,17,"Former"),
    (NULL,4,14,"Current"),
    (NULL,4,16,"Former"),
    (NULL,4,58,"Former"),
    (NULL,5,29,"Current"),
    (NULL,5,30,"Former"),
    (NULL,5,31,"Current"),
    (NULL,5,32,"Current"),
    (NULL,5,33,"Current"),
    (NULL,5,36,"Current"),
    (NULL,5,54,"Current"),
    (NULL,6,50,"Current"),
    (NULL,6,51,"Former"),
    (NULL,6,52,"Former"),
    (NULL,6,53,"Former"),
    (NULL,7,61,"Current"),
    (NULL,7,63,"Current"),
    (NULL,7,62,"Current"),
    (NULL,7,64,"Current"),
    (NULL,7,65,"Current"),
    (NULL,8,70,"Former"),
    (NULL,8,68,"Former"),
    (NULL,8,37,"Former");

SELECT Groups.name, Characters.first_name, Characters.last_name, Characters.alias, membership
FROM GroupCharacters
INNER JOIN Groups ON GroupCharacters.group_id = Groups.id
INNER JOIN Characters ON GroupCharacters.character_id = Characters.id;

DELETE FROM GroupCharacters;