INSERT INTO Characters
VALUES
    (NULL,"Anthony","Edward","Stark","1970-05-29","USA","Iron Man",1,1),
    (NULL,"James","Rupert","Rhodes","1968-10-06","USA","War Machine",1,1),
    (NULL,"Obadiah",NULL,"Stane",NULL,"USA","Iron Monger",1,1),
    (NULL,"Virginia",NULL,"Potts",NULL,"USA",NULL,1,2),
    (NULL,"Philip","J.","Coulson","1964-07-08","USA","Phil Coulson",1,1),
    (NULL,"Just A Rather Very Intelligent System",NULL,NULL,NULL,"USA","J.A.R.V.I.S.",15,1),
    (NULL,"Harold","Joseph","Hogan",NULL,"USA","Happy Hogan",1,1),
    (NULL,"Robert","Bruce","Banner","1969-12-18","USA","Hulk",1,1),
    (NULL,"Elizabeth",NULL,"Ross",NULL,"USA",NULL,1,2),
    (NULL,"Emil",NULL,"Blonsky","1971-03-01","Russia","Abomination",1,1),
    (NULL,"Natalia","Alianovna","Romanoff","1984-01-01","Russia","Black Widow",1,2),
    (NULL,"Ivan","Antonovich","Vanko","1968-02-15","Russia","Whiplash",1,1),
    (NULL,"Nicholas","Joseph","Fury","1950-07-04","USA","Nick Fury",1,1),
    (NULL,"Thor",NULL,"Odinson","964 A.D.","Asgard",NULL,2,1),
    (NULL,"Jane",NULL,"Foster",NULL,"USA",NULL,1,2),
    (NULL,"Loki",NULL,"Laufeyson","965 A.D.","Jotunheim",NULL,3,1),
    (NULL,"Odin",NULL,"Borson",NULL,"Asgard",NULL,2,1),
    (NULL,"Heimdall",NULL,NULL,NULL,"Asgard",NULL,2,1),
    (NULL,"Steven","Grant","Rogers","1918-07-04","USA","Captain America",1,1),
    (NULL,"James","Buchanan","Barnes","1917-03-10","USA","Winter Soldier",1,1),
    (NULL,"Johann",NULL,"Schmidt",NULL,"Germany","Red Skull",1,1),
    (NULL,"Clinton","Francis","Barton",NULL,"USA","Hawkeye",1,1),
    (NULL,"Maria",NULL,"Hill","1982-04-04","USA",NULL,1,2),
    (NULL,"Aldrich",NULL,"Killian",NULL,"USA","Mandarin",1,1),
    (NULL,"Malekith",NULL,NULL,NULL,"Svartalfheim",NULL,4,1),
    (NULL,"Algrim",NULL,NULL,NULL,"Svartalfheim","Kurse",4,1),
    (NULL,"Alexander","Goodwin","Pierce","1936-08-18","USA",NULL,1,1),
    (NULL,"Samuel","Thomas","Wilson",NULL,"USA","Falcon",1,1),
    (NULL,"Peter","Jason","Quill","1980-12-01","USA","Star-Lord",6,1),
    (NULL,"Gamora",NULL,NULL,NULL,"Zen-Whoberi",NULL,7,2),
    (NULL,"Drax",NULL,NULL,NULL,NULL,"Drax the Destroyer",18,1),
    (NULL,"Groot",NULL,NULL,NULL,"X",NULL,8,1),
    (NULL,"89P13",NULL,NULL,NULL,"Halfworld","Rocket",9,1),
    (NULL,"Ronan",NULL,NULL,NULL,"Hala","Ronan the Accuser",10,1),
    (NULL,"Yondu",NULL,"Udonta",NULL,"Centauri-IV",NULL,13,1),
    (NULL,"Nebula",NULL,NULL,NULL,"Luphom",NULL,12,2),
    (NULL,"Korath",NULL,NULL,NULL,"Hala","Korath the Pursuer",10,1),
    (NULL,"Ultron",NULL,NULL,"2015-05-01","USA",NULL,14,1),
    (NULL,"Pietro",NULL,"Maximoff",NULL,"Slovakia","Quicksilver",1,1),
    (NULL,"Wanda",NULL,"Maximoff",NULL,"Slovakia","Scarlet Witch",1,2),
    (NULL,"Vision",NULL,NULL,"2015-05-01","USA",NULL,13,1),
    (NULL,"Scott","Edward Harris","Lang",NULL,"USA","Ant-Man",1,1),
    (NULL,"Henry","Jonathan","Pym",NULL,"USA",NULL,1,1),
    (NULL,"Hope","van","Dyne","1980-01-01","USA","Wasp",1,2),
    (NULL,"Darren",NULL,"Cross",NULL,"USA","Yellowjacket",1,1),
    (NULL,"T'Challa",NULL,NULL,NULL,"Wakanda","Black Panther",1,1),
    (NULL,"Peter","Benjamin","Parker","2001-08-10","USA","Spider-Man",1,1),
    (NULL,"Helmut",NULL,"Zemo",NULL,"Sokovia",NULL,1,1),
    (NULL,"May",NULL,"Parker",NULL,"USA",NULL,1,2),
    (NULL,"Stephen","Vincent","Strange",NULL,"USA","Doctor Strange",1,1),
    (NULL,"Karl",NULL,"Mordo",NULL,"Romania",NULL,1,1),
    (NULL,"Kaecilius",NULL,NULL,NULL,"Denmark",NULL,1,1),
    (NULL,"Ancient One",NULL,NULL,"1317-01-01","Earth",NULL,1,2),
    (NULL,"Mantis",NULL,NULL,NULL,NULL,NULL,18,2),
    (NULL,"Ego",NULL,NULL,NULL,NULL,NULL,5,1),
    (NULL,"Adrian",NULL,"Toomes",NULL,"USA","Vulture",1,1),
    (NULL,"Michelle",NULL,"Jones","2001-06-10","USA",NULL,1,2),
    (NULL,"Hela",NULL,"Odinsdottir",NULL,"Asgard",NULL,2,2),
    (NULL,"Erik",NULL,"Stevens",NULL,"Wakanda","Killmonger",1,1),
    (NULL,"Okoye",NULL,NULL,NULL,"Wakanda",NULL,1,2),
    (NULL,"Thanos",NULL,NULL,"1013-01-01","Titan",NULL,16,1),
    (NULL,"Cull",NULL,"Obsidian",NULL,NULL,NULL,18,1),
    (NULL,"Ebony",NULL,"Maw",NULL,NULL,NULL,18,1),
    (NULL,"Proxima",NULL,"Midnight",NULL,NULL,NULL,18,2),
    (NULL,"Corvus",NULL,"Glaive",NULL,NULL,NULL,18,1),
    (NULL,"Sonny",NULL,"Burch",NULL,"USA",NULL,1,1),
    (NULL,"Ava",NULL,"Starr",NULL,"Britain","Ghost",1,2),
    (NULL,"Carol",NULL,"Danvers",NULL,"USA","Captain Marvel",11,2),
    (NULL,"Talos",NULL,NULL,NULL,"Skrullos",NULL,17,1),
    (NULL,"Yon-Rogg",NULL,NULL,NULL,"Hala",NULL,10,1),
    (NULL,"Quentin",NULL,"Beck",NULL,"USA","Mysterio",1,1);

SELECT * FROM Characters;
DELETE FROM Characters;