INSERT INTO Movies
VALUES
    (NULL,"Iron Man","2008-05-02",140000000,1,"After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil."),
    (NULL,"The Incredible Hulk","2008-06-13",150000000,1,"Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he turns into, whenever he loses his temper."),
    (NULL,"Iron Man 2","2010-05-07",170000000,1,"With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father's legacy."),
    (NULL,"Thor","2011-05-06",150000000,1,"The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders."),
    (NULL,"Captain America: The First Avenger","2011-07-22",140000000,1,"Steve Rogers, a rejected military soldier transforms into Captain America after taking a dose of a 'Super-Soldier serum'. But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization."),
    (NULL,"The Avengers","2012-05-04",220000000,1,"Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity."),
    (NULL,"Iron Man 3","2013-05-03",200000000,2,"When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution."),
    (NULL,"Thor: The Dark World","2013-11-08",170000000,2,"When the Dark Elves attempt to plunge the universe into darkness, Thor must embark on a perilous and personal journey that will reunite him with doctor Jane Foster."),
    (NULL,"Captain America: The Winter Soldier","2014-04-04",170000000,2,"As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier."),
    (NULL,"Guardians of the Galaxy","2014-08-01",200000000,2,"A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe."),
    (NULL,"Avengers: Age of Ultron","2015-05-01",365000000,2,"When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan."),
    (NULL,"Ant-Man","2015-07-17",130000000,2,"Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world."),
    (NULL,"Captain America: Civil War","2016-05-06",250000000,3,"Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man."),
    (NULL,"Doctor Strange","2016-11-04",165000000,3,"While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts."),
    (NULL,"Guardians of the Galaxy Vol. 2","2017-05-05",200000000,3,"The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father the ambitious celestial being Ego."),
    (NULL,"Spider-Man: Homecoming","2017-07-07",175000000,3,"Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City."),
    (NULL,"Thor: Ragnarok","2017-11-03",180000000,3,"Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela."),
    (NULL,"Black Panther","2018-02-16",200000000,3,"T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past."),
    (NULL,"Avengers: Infinity War","2018-04-27",316000000,3,"The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe."),
    (NULL,"Ant-Man and the Wasp","2018-07-06",162000000,3,"As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past."),
    (NULL,"Captain Marvel","2019-03-08",152000000,3,"Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races."),
    (NULL,"Avengers: Endgame","2019-04-26",356000000,3,"After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe."),
    (NULL,"Spider-Man: Far From Home","2019-07-02",160000000,3,"Following the events of Avengers: Endgame (2019), Spider-Man must step up to take on new threats in a world that has changed forever.");

DELETE FROM Movies;
SELECT * FROM Movies;